/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as RegisterRouteImport } from './routes/register'
import { Route as LoginRouteImport } from './routes/login'
import { Route as ForgotPasswordRouteImport } from './routes/forgot-password'
import { Route as AppRouteImport } from './routes/_app'
import { Route as AppIndexRouteImport } from './routes/_app/index'
import { Route as AppUploadRouteImport } from './routes/_app/upload'
import { Route as AppSubscribersRouteImport } from './routes/_app/subscribers'
import { Route as AppSettingsRouteImport } from './routes/_app/settings'
import { Route as AppPlaylistsRouteImport } from './routes/_app/playlists'
import { Route as AppMyContentRouteImport } from './routes/_app/my-content'
import { Route as AppLikedVideosRouteImport } from './routes/_app/liked-videos'
import { Route as AppHistoryRouteImport } from './routes/_app/history'
import { Route as AppHelpRouteImport } from './routes/_app/help'
import { Route as AppDashboardRouteImport } from './routes/_app/dashboard'
import { Route as AppWatchVideoIdRouteImport } from './routes/_app/watch.$videoId'
import { Route as AppChannelUserNameRouteImport } from './routes/_app/channel.$userName'

const RegisterRoute = RegisterRouteImport.update({
  id: '/register',
  path: '/register',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const ForgotPasswordRoute = ForgotPasswordRouteImport.update({
  id: '/forgot-password',
  path: '/forgot-password',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRoute = AppRouteImport.update({
  id: '/_app',
  getParentRoute: () => rootRouteImport,
} as any)
const AppIndexRoute = AppIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppRoute,
} as any)
const AppUploadRoute = AppUploadRouteImport.update({
  id: '/upload',
  path: '/upload',
  getParentRoute: () => AppRoute,
} as any)
const AppSubscribersRoute = AppSubscribersRouteImport.update({
  id: '/subscribers',
  path: '/subscribers',
  getParentRoute: () => AppRoute,
} as any)
const AppSettingsRoute = AppSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AppRoute,
} as any)
const AppPlaylistsRoute = AppPlaylistsRouteImport.update({
  id: '/playlists',
  path: '/playlists',
  getParentRoute: () => AppRoute,
} as any)
const AppMyContentRoute = AppMyContentRouteImport.update({
  id: '/my-content',
  path: '/my-content',
  getParentRoute: () => AppRoute,
} as any)
const AppLikedVideosRoute = AppLikedVideosRouteImport.update({
  id: '/liked-videos',
  path: '/liked-videos',
  getParentRoute: () => AppRoute,
} as any)
const AppHistoryRoute = AppHistoryRouteImport.update({
  id: '/history',
  path: '/history',
  getParentRoute: () => AppRoute,
} as any)
const AppHelpRoute = AppHelpRouteImport.update({
  id: '/help',
  path: '/help',
  getParentRoute: () => AppRoute,
} as any)
const AppDashboardRoute = AppDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AppRoute,
} as any)
const AppWatchVideoIdRoute = AppWatchVideoIdRouteImport.update({
  id: '/watch/$videoId',
  path: '/watch/$videoId',
  getParentRoute: () => AppRoute,
} as any)
const AppChannelUserNameRoute = AppChannelUserNameRouteImport.update({
  id: '/channel/$userName',
  path: '/channel/$userName',
  getParentRoute: () => AppRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof AppIndexRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/login': typeof LoginRoute
  '/register': typeof RegisterRoute
  '/dashboard': typeof AppDashboardRoute
  '/help': typeof AppHelpRoute
  '/history': typeof AppHistoryRoute
  '/liked-videos': typeof AppLikedVideosRoute
  '/my-content': typeof AppMyContentRoute
  '/playlists': typeof AppPlaylistsRoute
  '/settings': typeof AppSettingsRoute
  '/subscribers': typeof AppSubscribersRoute
  '/upload': typeof AppUploadRoute
  '/channel/$userName': typeof AppChannelUserNameRoute
  '/watch/$videoId': typeof AppWatchVideoIdRoute
}
export interface FileRoutesByTo {
  '/forgot-password': typeof ForgotPasswordRoute
  '/login': typeof LoginRoute
  '/register': typeof RegisterRoute
  '/dashboard': typeof AppDashboardRoute
  '/help': typeof AppHelpRoute
  '/history': typeof AppHistoryRoute
  '/liked-videos': typeof AppLikedVideosRoute
  '/my-content': typeof AppMyContentRoute
  '/playlists': typeof AppPlaylistsRoute
  '/settings': typeof AppSettingsRoute
  '/subscribers': typeof AppSubscribersRoute
  '/upload': typeof AppUploadRoute
  '/': typeof AppIndexRoute
  '/channel/$userName': typeof AppChannelUserNameRoute
  '/watch/$videoId': typeof AppWatchVideoIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_app': typeof AppRouteWithChildren
  '/forgot-password': typeof ForgotPasswordRoute
  '/login': typeof LoginRoute
  '/register': typeof RegisterRoute
  '/_app/dashboard': typeof AppDashboardRoute
  '/_app/help': typeof AppHelpRoute
  '/_app/history': typeof AppHistoryRoute
  '/_app/liked-videos': typeof AppLikedVideosRoute
  '/_app/my-content': typeof AppMyContentRoute
  '/_app/playlists': typeof AppPlaylistsRoute
  '/_app/settings': typeof AppSettingsRoute
  '/_app/subscribers': typeof AppSubscribersRoute
  '/_app/upload': typeof AppUploadRoute
  '/_app/': typeof AppIndexRoute
  '/_app/channel/$userName': typeof AppChannelUserNameRoute
  '/_app/watch/$videoId': typeof AppWatchVideoIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/forgot-password'
    | '/login'
    | '/register'
    | '/dashboard'
    | '/help'
    | '/history'
    | '/liked-videos'
    | '/my-content'
    | '/playlists'
    | '/settings'
    | '/subscribers'
    | '/upload'
    | '/channel/$userName'
    | '/watch/$videoId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/forgot-password'
    | '/login'
    | '/register'
    | '/dashboard'
    | '/help'
    | '/history'
    | '/liked-videos'
    | '/my-content'
    | '/playlists'
    | '/settings'
    | '/subscribers'
    | '/upload'
    | '/'
    | '/channel/$userName'
    | '/watch/$videoId'
  id:
    | '__root__'
    | '/_app'
    | '/forgot-password'
    | '/login'
    | '/register'
    | '/_app/dashboard'
    | '/_app/help'
    | '/_app/history'
    | '/_app/liked-videos'
    | '/_app/my-content'
    | '/_app/playlists'
    | '/_app/settings'
    | '/_app/subscribers'
    | '/_app/upload'
    | '/_app/'
    | '/_app/channel/$userName'
    | '/_app/watch/$videoId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AppRoute: typeof AppRouteWithChildren
  ForgotPasswordRoute: typeof ForgotPasswordRoute
  LoginRoute: typeof LoginRoute
  RegisterRoute: typeof RegisterRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/register': {
      id: '/register'
      path: '/register'
      fullPath: '/register'
      preLoaderRoute: typeof RegisterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/forgot-password': {
      id: '/forgot-password'
      path: '/forgot-password'
      fullPath: '/forgot-password'
      preLoaderRoute: typeof ForgotPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app': {
      id: '/_app'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/': {
      id: '/_app/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AppIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/upload': {
      id: '/_app/upload'
      path: '/upload'
      fullPath: '/upload'
      preLoaderRoute: typeof AppUploadRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/subscribers': {
      id: '/_app/subscribers'
      path: '/subscribers'
      fullPath: '/subscribers'
      preLoaderRoute: typeof AppSubscribersRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/settings': {
      id: '/_app/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof AppSettingsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/playlists': {
      id: '/_app/playlists'
      path: '/playlists'
      fullPath: '/playlists'
      preLoaderRoute: typeof AppPlaylistsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/my-content': {
      id: '/_app/my-content'
      path: '/my-content'
      fullPath: '/my-content'
      preLoaderRoute: typeof AppMyContentRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/liked-videos': {
      id: '/_app/liked-videos'
      path: '/liked-videos'
      fullPath: '/liked-videos'
      preLoaderRoute: typeof AppLikedVideosRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/history': {
      id: '/_app/history'
      path: '/history'
      fullPath: '/history'
      preLoaderRoute: typeof AppHistoryRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/help': {
      id: '/_app/help'
      path: '/help'
      fullPath: '/help'
      preLoaderRoute: typeof AppHelpRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/dashboard': {
      id: '/_app/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AppDashboardRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/watch/$videoId': {
      id: '/_app/watch/$videoId'
      path: '/watch/$videoId'
      fullPath: '/watch/$videoId'
      preLoaderRoute: typeof AppWatchVideoIdRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/channel/$userName': {
      id: '/_app/channel/$userName'
      path: '/channel/$userName'
      fullPath: '/channel/$userName'
      preLoaderRoute: typeof AppChannelUserNameRouteImport
      parentRoute: typeof AppRoute
    }
  }
}

interface AppRouteChildren {
  AppDashboardRoute: typeof AppDashboardRoute
  AppHelpRoute: typeof AppHelpRoute
  AppHistoryRoute: typeof AppHistoryRoute
  AppLikedVideosRoute: typeof AppLikedVideosRoute
  AppMyContentRoute: typeof AppMyContentRoute
  AppPlaylistsRoute: typeof AppPlaylistsRoute
  AppSettingsRoute: typeof AppSettingsRoute
  AppSubscribersRoute: typeof AppSubscribersRoute
  AppUploadRoute: typeof AppUploadRoute
  AppIndexRoute: typeof AppIndexRoute
  AppChannelUserNameRoute: typeof AppChannelUserNameRoute
  AppWatchVideoIdRoute: typeof AppWatchVideoIdRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppDashboardRoute: AppDashboardRoute,
  AppHelpRoute: AppHelpRoute,
  AppHistoryRoute: AppHistoryRoute,
  AppLikedVideosRoute: AppLikedVideosRoute,
  AppMyContentRoute: AppMyContentRoute,
  AppPlaylistsRoute: AppPlaylistsRoute,
  AppSettingsRoute: AppSettingsRoute,
  AppSubscribersRoute: AppSubscribersRoute,
  AppUploadRoute: AppUploadRoute,
  AppIndexRoute: AppIndexRoute,
  AppChannelUserNameRoute: AppChannelUserNameRoute,
  AppWatchVideoIdRoute: AppWatchVideoIdRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  AppRoute: AppRouteWithChildren,
  ForgotPasswordRoute: ForgotPasswordRoute,
  LoginRoute: LoginRoute,
  RegisterRoute: RegisterRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
